# Site settings
title: Radu Chiriac
email: contact@raduchiriac.me

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://blog.raduchiriac.me' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          false
paginate:            10
paginate_path:       page/:num/

sass:
    sass_dir: _sass
    sourcemap: true
    style:    compressed

defaults:
  -
      scope:
        path: "_posts"
        type: "posts"
      values:
        reading_time: true
        show_tags: true
        show_categories: true
